### ISSUE TITLE
The API key is committed in the repository.

### ISSUE THREAD

**Issue by atoivonen** [koalaty-code/weather-grabber-dotnet-core#1]
Is there a easy way to refactor to remove the api key from source control?

**Comment by koalaty-code** [comment]
Hi @atoivonen,
I apologize for the delayed response. I was not notified that an issue was opened. 

An easy way to rid the API key from source control would be to use an environment variable. Would you like me to implement such a solution?

**Comment by atoivonen** [comment]
Hi @koalaty-code - I think an environment variable would be a good approach.  I don't think there is a need to implement that functionality at this time.
